### ISSUE TITLE
I get very strange constant  Sending state 450000.00000 W  readings.

### ISSUE THREAD

**Issue by geeneo** [klaasnicolaas/home-assistant-glow#47] opened 2021-09-08 06:49 UTC
Hi

I get very strange constant  Sending state 450000.00000 W  readings, anyone also get this. Not sure where to begin.

See my debug log,

[D][sensor:131]: 'House - Power consumption': Sending state 2310.65454 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.05300 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2298.85059 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.05400 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.05400 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2282.81543 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.05600 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2282.81543 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.05800 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
**[D][sensor:131]: 'House - Power consumption': Sending state 2271.29346 W with 0 decimals of accuracy**
[D][sensor:131]: 'House - Total energy': Sending state 0.05900 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06100 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06300 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2271.29346 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06400 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06400 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2282.81543 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06600 kWh with 3 decimals of accuracy
**[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy**
[D][sensor:131]: 'House - Power consumption': Sending state 2271.29346 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06700 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.06800 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2282.81543 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.07000 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2282.81543 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.07200 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 450000.00000 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Power consumption': Sending state 2271.29346 W with 0 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.07300 kWh with 3 decimals of accuracy
[D][sensor:131]: 'House - Total energy': Sending state 0.07300 kWh with 3 decimals of accuracy

**Comment by KixMan28** [comment] 2021-09-08 08:24
Please check issue #34.

**Comment by dominicknoetze** [comment] 2021-09-08 16:51
Try setting the sensitivity on you photo diode.I had a similar problem and fine tuning it solved my problem.

**Comment by mrwhite31** [comment] 2021-09-11 16:30
I am also getting this high value readings regularly. 600.000W, 450.000W, 900.000W... Every flash on the meter is detected correctly and the red led is flashing. Not sure why I am getting those glitches. How did you do the fine tuning on the photodiode?

**Comment by KixMan28** [comment] 2021-09-11 16:37
@mrwhite31 you have a potentiometer on your module (blue box with gray screw top). Try adjusting that. Please check your photodiode if it soldered correctly. Many of us had the photodiode soldered in reverse. Check issue #34 for details.

**Comment by mrwhite31** [comment] 2021-09-11 18:50
@KixMan28 thanks. I've alteady adjusted the potentiometer to the lowest possible sensitivity that it is still catching the flashes. Isn't that correct? 
the diode is soldered the correct way. Also tried other modules.
I forgot to mention that it started not too long ago. It ran fine and without glitches for one and a half month before

**Comment by KixMan28** [comment] 2021-09-11 20:00
@mrwhite31 Sorry, I cannot help you further. I had similar issues when my photodiode was soldered in reverse. Since I re-soldered it everything works as intended.

**Comment by jLynx** [comment] 2021-09-12 06:12
Try adding this 
```internal_filter: 100ms```

**Comment by mrwhite31** [comment] 2021-09-13 16:07
@jLynx adding internal_filter solved it, thanks!

**Comment by klaasnicolaas** [comment] 2021-09-15 22:34
I think we can close the issue then?

**Comment by jLynx** [comment] 2021-09-15 22:41
@klaasnicolaas please close this issue

**Closed** 2021-09-15 22:57 UTC
