### ISSUE TITLE
Calibrate total consumption

### ISSUE THREAD

**Issue by naofireblade** [klaasnicolaas/home-assistant-glow#264] opened 2023-01-14 22:04 UTC
I‘d like to have a way to calibrate the total consumption sensor value. So that the total on glow is the same total as on the real energy meter.

**Comment by klaasnicolaas** [comment] 2023-01-14 22:14
I think this is a duplicate of: https://github.com/klaasnicolaas/home-assistant-glow/discussions/190

**Comment by naofireblade** [comment] 2023-01-15 10:12
Correct, sorry. Will try to provide a PR.

**Closed** 2023-01-15 10:13 UTC
